spring.application.name=@project.artifactId@
spring.application.description=@project.description@
spring.application.version=@project.version@

logging.level.root=${LOG_LEVEL:info}
spring.output.ansi.enabled=ALWAYS

## Rest Template
logging.level.org.springframework.web.client.RestTemplate=${LOG_LEVEL:info}
rest-template.timeout=${REST_TEMPLATE_TIMEOUT}

## Jackson
spring.jackson.property-naming-strategy=${JSON_PROPERTY_STRATEGY}
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.default-property-inclusion=non_null

## Mongo DB
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
